# Generated by Django 6.0.7 on 2026-08-02 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily')], db_index=True, default='daily', max_length=10)),
                ('period_start', models.DateTimeField(db_index=True)),
                ('period_end', models.DateTimeField()),
                ('total_incidents', models.PositiveIntegerField(default=0)),
                ('by_type', models.JSONField(default=dict)),
                ('by_state', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_reports', to='roads.roadsegment')),
            ],
            options={
                'verbose_name': 'Incident Report',
                'verbose_name_plural': 'Incident Reports',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['period_type', 'period_start'], name='analytics_inc_type_start_idx')],
                'constraints': [models.UniqueConstraint(fields=('segment', 'period_type', 'period_start'), name='analytics_inc_segment_type_start_uniq')],
            },
        ),
        migrations.CreateModel(
            name='TrafficFlowSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily')], db_index=True, max_length=10)),
                ('period_start', models.DateTimeField(db_index=True)),
                ('period_end', models.DateTimeField()),
                ('total_vehicle_count', models.PositiveIntegerField(blank=True, null=True)),
                ('avg_speed_kmh', models.FloatField(blank=True, null=True)),
                ('avg_occupancy_pct', models.FloatField(blank=True, null=True)),
                ('sample_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flow_summaries', to='roads.roadsegment')),
            ],
            options={
                'verbose_name': 'Traffic Flow Summary',
                'verbose_name_plural': 'Traffic Flow Summaries',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['period_type', 'period_start'], name='analytics_flow_type_start_idx')],
                'constraints': [models.UniqueConstraint(fields=('segment', 'period_type', 'period_start'), name='analytics_flow_segment_type_start_uniq')],
            },
        ),
        migrations.CreateModel(
            name='ViolationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily')], db_index=True, default='daily', max_length=10)),
                ('period_start', models.DateTimeField(db_index=True)),
                ('period_end', models.DateTimeField()),
                ('total_violations', models.PositiveIntegerField(default=0)),
                ('by_type', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violation_summaries', to='roads.roadsegment')),
            ],
            options={
                'verbose_name': 'Violation Summary',
                'verbose_name_plural': 'Violation Summaries',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['period_type', 'period_start'], name='analytics_viol_type_start_idx')],
                'constraints': [models.UniqueConstraint(fields=('segment', 'period_type', 'period_start'), name='analytics_viol_segment_type_start_uniq')],
            },
        ),
    ]
