# Generated by Django 6.0.7 on 2026-08-02 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=30)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('motorcycle', 'Motorcycle'), ('truck', 'Truck'), ('bus', 'Bus'), ('van', 'Van'), ('bicycle', 'Bicycle'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('registration_country', models.CharField(blank=True, default='', max_length=60)),
                ('color', models.CharField(blank=True, default='', max_length=50)),
                ('make', models.CharField(blank=True, default='', max_length=100)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('year', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1886), django.core.validators.MaxValueValidator(2100)])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vehicle_type', 'is_active'], name='vio_veh_type_active_idx')],
            },
        ),
    ]
