# Generated by Django 6.0.7 on 2026-08-02 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
        ('roads', '0001_initial'),
        ('violations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('speeding', 'Speeding'), ('red_light', 'Red Light'), ('illegal_parking', 'Illegal Parking'), ('wrong_way', 'Wrong Way'), ('illegal_turn', 'Illegal Turn'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='cameras.camera')),
                ('intersection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='roads.intersection')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_violations', to=settings.AUTH_USER_MODEL)),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='roads.roadsegment')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='violations', to='violations.vehicle')),
            ],
            options={
                'verbose_name': 'Traffic Violation',
                'verbose_name_plural': 'Traffic Violations',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField()),
                ('state', models.CharField(choices=[('issued', 'Issued'), ('contested', 'Contested'), ('adjudicated', 'Adjudicated')], db_index=True, default='issued', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_citations', to=settings.AUTH_USER_MODEL)),
                ('violation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='citation', to='violations.trafficviolation')),
            ],
            options={
                'verbose_name': 'Citation',
                'verbose_name_plural': 'Citations',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='ViolationEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('sensor_reading', 'Sensor Reading')], db_index=True, default='image', max_length=20)),
                ('evidence_url', models.URLField(help_text='External object-storage URL (S3, CDN, etc.). No binary data stored here.', max_length=2048)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='violations.trafficviolation')),
            ],
            options={
                'verbose_name': 'Violation Evidence',
                'verbose_name_plural': 'Violation Evidence',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='trafficviolation',
            index=models.Index(fields=['violation_type', 'is_active'], name='vio_tv_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficviolation',
            index=models.Index(fields=['vehicle', 'occurred_at'], name='vio_tv_vehicle_time_idx'),
        ),
        migrations.AddIndex(
            model_name='citation',
            index=models.Index(fields=['state'], name='vio_cit_state_idx'),
        ),
        migrations.AddIndex(
            model_name='violationevidence',
            index=models.Index(fields=['violation', 'evidence_type'], name='vio_evid_viol_type_idx'),
        ),
    ]
