# Generated by Django 6.0.7 on 2026-08-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0002_add_violation_evidence_citation'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficviolation',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trafficviolation',
            name='model_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='trafficviolation',
            name='model_version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='trafficviolation',
            name='review_status',
            field=models.CharField(choices=[('auto_accepted', 'Auto Accepted'), ('pending', 'Pending Review'), ('low_confidence', 'Low Confidence'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='verified', max_length=20),
        ),
        migrations.AddField(
            model_name='trafficviolation',
            name='source',
            field=models.CharField(choices=[('ai', 'AI Generated'), ('manual', 'Manually Entered')], db_index=True, default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='violationevidence',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
