# Generated by Django 6.0.7 on 2026-08-01 08:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('controller_type', models.CharField(blank=True, default='', max_length=100)),
                ('controller_identifier', models.CharField(blank=True, default='', max_length=150)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traffic_signals', to='roads.intersection')),
            ],
            options={
                'verbose_name': 'Traffic Signal',
                'verbose_name_plural': 'Traffic Signals',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SignalPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('name', models.CharField(max_length=100)),
                ('movement', models.CharField(blank=True, default='', max_length=150)),
                ('minimum_green_seconds', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('maximum_green_seconds', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('yellow_seconds', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('all_red_seconds', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phases', to='traffic.trafficsignal')),
            ],
            options={
                'verbose_name': 'Signal Phase',
                'verbose_name_plural': 'Signal Phases',
                'ordering': ['signal', 'phase_number'],
            },
        ),
        migrations.AddIndex(
            model_name='trafficsignal',
            index=models.Index(fields=['intersection', 'is_active'], name='traffic_sig_int_active_idx'),
        ),
        migrations.AddIndex(
            model_name='signalphase',
            index=models.Index(fields=['signal', 'is_active'], name='traffic_phase_sig_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='signalphase',
            unique_together={('signal', 'phase_number')},
        ),
    ]
