# Generated by Django 6.0.7 on 2026-08-01 10:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
        ('roads', '0001_initial'),
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateTimeField(db_index=True)),
                ('vehicle_count', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('avg_speed_kmh', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('occupancy_pct', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurements', to='cameras.camera')),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurements', to='roads.roadsegment')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurements', to='cameras.sensor')),
            ],
            options={
                'verbose_name': 'Traffic Measurement',
                'verbose_name_plural': 'Traffic Measurements',
                'ordering': ['-measured_at'],
                'indexes': [models.Index(fields=['segment', 'measured_at'], name='traffic_meas_seg_time_idx'), models.Index(fields=['camera', 'measured_at'], name='traffic_meas_cam_time_idx'), models.Index(fields=['sensor', 'measured_at'], name='traffic_meas_sen_time_idx')],
            },
        ),
    ]
