# Generated by Django 6.0.7 on 2026-08-02 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0001_initial'),
        ('traffic', '0002_add_traffic_measurement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('congestion', 'Congestion'), ('incident', 'Incident'), ('roadwork', 'Roadwork'), ('weather', 'Weather Hazard'), ('signal_fault', 'Signal Fault'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('description', models.TextField()),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traffic_events', to=settings.AUTH_USER_MODEL)),
                ('intersection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traffic_events', to='roads.intersection')),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traffic_events', to='roads.roadsegment')),
            ],
            options={
                'verbose_name': 'Traffic Event',
                'verbose_name_plural': 'Traffic Events',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['event_type', 'is_active'], name='traffic_evt_type_active_idx'), models.Index(fields=['segment', 'occurred_at'], name='traffic_evt_seg_time_idx'), models.Index(fields=['intersection', 'occurred_at'], name='traffic_evt_int_time_idx')],
            },
        ),
    ]
