# Generated by Django 6.0.7 on 2026-08-02 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0001_initial'),
        ('traffic', '0003_add_traffic_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('incident_type', models.CharField(choices=[('accident', 'Accident'), ('road_closure', 'Road Closure'), ('hazard', 'Hazard'), ('flooding', 'Flooding'), ('fire', 'Fire'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('state', models.CharField(choices=[('reported', 'Reported'), ('investigating', 'Investigating'), ('managing', 'Managing'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='reported', max_length=20)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to=settings.AUTH_USER_MODEL)),
                ('intersection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='roads.intersection')),
                ('segments', models.ManyToManyField(blank=True, related_name='incidents', to='roads.roadsegment')),
            ],
            options={
                'verbose_name': 'Traffic Incident',
                'verbose_name_plural': 'Traffic Incidents',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['state', 'is_active'], name='traffic_inc_state_active_idx'), models.Index(fields=['incident_type', 'state'], name='traffic_inc_type_state_idx')],
            },
        ),
    ]
