# Generated by Django 6.0.7 on 2026-08-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0004_add_traffic_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficmeasurement',
            name='data_source',
            field=models.CharField(choices=[('ai', 'AI Service'), ('sensor', 'Physical Sensor'), ('manual', 'Manual Entry'), ('demo', 'Demo / Seed Data')], db_index=True, default='demo', max_length=10),
        ),
    ]
