# Generated by Django 6.0.7 on 2026-08-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('driver_identifier', models.CharField(blank=True, default='', max_length=120)),
                ('license_number', models.CharField(max_length=80, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('license_status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('pending', 'Pending')], db_index=True, default='active', max_length=20)),
                ('license_issue_date', models.DateField(blank=True, null=True)),
                ('license_expiry_date', models.DateField(blank=True, null=True)),
                ('registration_status', models.CharField(choices=[('registered', 'Registered'), ('unregistered', 'Unregistered'), ('pending', 'Pending')], db_index=True, default='registered', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
