# Generated by Django 6.0.7 on 2026-07-31 20:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intersection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('latitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Intersection',
                'verbose_name_plural': 'Intersections',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('road_type', models.CharField(choices=[('motorway', 'Motorway'), ('primary', 'Primary Road'), ('secondary', 'Secondary Road'), ('tertiary', 'Tertiary Road'), ('residential', 'Residential'), ('service', 'Service Road'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Road',
                'verbose_name_plural': 'Roads',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoadSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('length_meters', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('speed_limit_kmh', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)])),
                ('lane_count', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('direction', models.CharField(choices=[('bidirectional', 'Bidirectional'), ('one_way_forward', 'One-way (Forward)'), ('one_way_reverse', 'One-way (Reverse)')], default='bidirectional', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('end_intersection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_segments', to='roads.intersection')),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='segments', to='roads.road')),
                ('start_intersection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_segments', to='roads.intersection')),
            ],
            options={
                'verbose_name': 'Road Segment',
                'verbose_name_plural': 'Road Segments',
                'ordering': ['road', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Lane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('lane_type', models.CharField(choices=[('travel', 'Travel Lane'), ('turn_left', 'Left Turn Lane'), ('turn_right', 'Right Turn Lane'), ('bus', 'Bus Lane'), ('cycle', 'Cycle Lane'), ('emergency', 'Emergency Lane'), ('parking', 'Parking Lane'), ('other', 'Other')], db_index=True, default='travel', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lanes', to='roads.roadsegment')),
            ],
            options={
                'verbose_name': 'Lane',
                'verbose_name_plural': 'Lanes',
                'ordering': ['segment', 'lane_number'],
            },
        ),
        migrations.AddIndex(
            model_name='roadsegment',
            index=models.Index(fields=['road', 'is_active'], name='roads_seg_road_active_idx'),
        ),
        migrations.AddIndex(
            model_name='lane',
            index=models.Index(fields=['segment', 'is_active'], name='roads_lane_seg_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lane',
            unique_together={('segment', 'lane_number')},
        ),
    ]
