# Generated by Django 6.0.7 on 2026-07-31 21:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('camera_type', models.CharField(choices=[('fixed', 'Fixed Camera'), ('ptz', 'PTZ (Pan-Tilt-Zoom)'), ('thermal', 'Thermal Camera'), ('other', 'Other')], db_index=True, default='fixed', max_length=20)),
                ('model', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('stream_url', models.URLField(blank=True, default='', max_length=1024)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intersection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='roads.intersection')),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='roads.roadsegment')),
            ],
            options={
                'verbose_name': 'Camera',
                'verbose_name_plural': 'Cameras',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('sensor_type', models.CharField(choices=[('inductive_loop', 'Inductive Loop'), ('radar', 'Radar'), ('lidar', 'LiDAR'), ('infrared', 'Infrared'), ('acoustic', 'Acoustic'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('model', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intersection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to='roads.intersection')),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to='roads.roadsegment')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CameraHealth',
            fields=[
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='health', serialize=False, to='cameras.camera')),
                ('health_status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('offline', 'Offline'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=16)),
                ('connectivity_status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=16)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('detail', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Camera Health',
                'verbose_name_plural': 'Camera Health Records',
            },
        ),
        migrations.CreateModel(
            name='SensorHealth',
            fields=[
                ('sensor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='health', serialize=False, to='cameras.sensor')),
                ('health_status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('offline', 'Offline'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=16)),
                ('connectivity_status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=16)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('detail', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Sensor Health',
                'verbose_name_plural': 'Sensor Health Records',
            },
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['segment', 'is_active'], name='cams_cam_seg_active_idx'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['intersection', 'is_active'], name='cams_cam_int_active_idx'),
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['segment', 'is_active'], name='cams_sen_seg_active_idx'),
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['intersection', 'is_active'], name='cams_sen_int_active_idx'),
        ),
    ]
