# Generated by Django 6.0.7 on 2026-08-03 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='hls_path',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='camera',
            name='stream_url',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.CreateModel(
            name='CameraCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('password', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='cameras.camera')),
            ],
            options={
                'verbose_name': 'Camera Credential',
                'verbose_name_plural': 'Camera Credentials',
            },
        ),
    ]
