# Generated by Django 6.0.7 on 2026-08-04 12:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_phase5_rtsp_credential'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meters_per_pixel', models.FloatField(help_text="Real-world metres per pixel in the camera's field of view. Must be measured from a known reference object in the scene.")),
                ('calibrated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calibrated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera_calibrations', to=settings.AUTH_USER_MODEL)),
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calibration', to='cameras.camera')),
            ],
            options={
                'verbose_name': 'Camera Calibration',
                'verbose_name_plural': 'Camera Calibrations',
            },
        ),
    ]
