# Generated by Django 6.0.7 on 2026-08-04 20:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_phase5_calibration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserWebcamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('device_label', models.CharField(blank=True, default='', help_text='Browser MediaDeviceInfo.label — for display only, never used server-side for auth.', max_length=255)),
                ('source_type', models.CharField(default='browser_webcam', editable=False, max_length=32)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('vehicle_count_total', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webcam_sessions', to='cameras.camera')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webcam_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Browser Webcam Session',
                'verbose_name_plural': 'Browser Webcam Sessions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='cams_bws_user_active_idx')],
            },
        ),
    ]
