# Generated by Django 6.0.7 on 2026-08-05 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0004_phase5c_browser_webcam_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='browserwebcamsession',
            name='camera',
            field=models.ForeignKey(blank=True, help_text='Optional reference to a registered camera when available; browser webcam sessions do not require a camera record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webcam_sessions', to='cameras.camera'),
        ),
        migrations.CreateModel(
            name='TemporaryVideoAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('upload', models.FileField(upload_to='uploads/tmp_videos/%Y/%m/%d')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('result_json', models.JSONField(blank=True, null=True)),
                ('annotated_video', models.FileField(blank=True, null=True, upload_to='uploads/annotated_videos/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Temporary Video Analysis',
                'verbose_name_plural': 'Temporary Video Analyses',
            },
        ),
    ]
